{
        "building":{
                    "0":"None",
                    "1":"The_Senate",
                    "2":"Judgment_Central",
                    "3":"Enforcer_Academy",
                    "4":"Law_Control_Station",
                    "5":"Megastation_One",
                    "6":"Megastation_Two",
                    "7":"Phoenix_Sanatorium",
                    "8":"Nightingale_Tower",
                    "9":"Iliad_Institute",
                    "10":"Bosch_Institute",
                    "11":"Marge_Piercy_Academy",
                    "12":"Rescue_One",
                    "13":"Rescue_Two",
                    "14":"Rescue_Three",
                    "15":"Quadrax_Tower",
                    "16":"Gygax_Memorial_Building",
                    "17":"Parallax_Tower",
                    "18":"Tsunami_Building",
                    "19":"Venus_Spires",
                    "20":"Raven_Reaches",
                    "21":"Mahler_Building",
                    "22":"The_Gugarin_Institute",
                    "23":"Lincoln_Tower",
                    "24":"The_Armageddon_Centre",
                    "25":"Cyborg_Institute",
                    "26":"Uhuru_Tower",
                    "27":"The_Karpov_Building",
                    "28":"Nietzsche_Institute",
                    "29":"Foucault_Tower",
                    "30":"Edifice_Tower",
                    "31":"The_Ozone_Building",
                    "32":"The_New_Empire_Tower",
                    "33":"Descartes_Towers",
                    "34":"Transtellar_Spacelines",
                    "35":"Galactic_Central",
                    "36":"Megavision_One",
                    "37":"Megavision_Two",
                    "38":"Megavision_Three",
                    "39":"Megatribe_Warriors",
                    "40":"Meteor_Kings",
                    "41":"Dog_Star_Wanderers",
                    "42":"Garden_of_Delights",
                    "43":"The_Lineage_Foundation",
                    "44":"Aldous_Huxley_Emporium",
                    "45":"Hypermart_Zone",
                    "46":"Acropolis_Apartments",
                    "47":"Atlantis_Apartments",
                    "48":"Babylon_Apartments",
                    "49":"Ptolemy_Apartments",
                    "50":"Habizone_Apartments",
                    "51":"Ecozone_Apartments",
                    "52":"Stellar_Apartments",
                    "53":"Lone_Ranger_Apartments",
                    "54":"Eden_Mansions",
                    "55":"Utopia_Mansions",
                    "56":"Nirvana_Mansions",
                    "57":"Cyclops_Mansions",
                    "58":"Cultivator_One",
                    "59":"Cultivator_Two",
                    "60":"Cultivator_Three",
                    "61":"Cityclean_One",
                    "62":"Cityclean_Two",
                    "63":"Cityclean_Three",
                    "64":"Hydrozone_One",
                    "65":"Hydrozone_Two",
                    "66":"Hydrozone_Three",
                    "67":"Appliances_One",
                    "68":"Appliances_Two",
                    "69":"Appliances_Three",
                    "70":"Arms_One",
                    "71":"Arms_Two",
                    "72":"Arms_Three",
                    "73":"Robot_One",
                    "74":"Robot_Two",
                    "75":"Robot_Three",
                    "76":"Car_One",
                    "77":"Car_Two",
                    "78":"Car_Three",
                    "79":"Flyer_One",
                    "80":"Flyer_Two",
                    "81":"Flyer_Three",
                    "82":"Megaflyer_One",
                    "83":"Megaflyer_Two",
                    "84":"Megaflyer_Three",
                    "85":"Construction_One",
                    "86":"Construction_Two",
                    "87":"Construction_Three",
                    "88":"George_Orwell_Block",
                    "89":"Thomas_More_Tower",
                    "90":"Dickens_Estate",
                    "91":"Oliver_Twist_Block",
                    "92":"Campesino_Apartments",
                    "93":"Grey_Visitor_Towers",
                    "94":"Scrooge_Mansions",
                    "95":"Borstal_Block",
                    "96":"Heavenly_Towers",
                    "97":"Civic_Project",
                    "98":"Chronos_Block",
                    "99":"Necronomicon_Mansions",
                    "100":"Angel_Heart_Heights",
                    "101":"Lovecraft_Block",
                    "102":"Bakunin_Block",
                    "103":"Saturn_Block",
                    "104":"Hades_Block",
                    "105":"Neptune_Towers",
                    "106":"Maze_Towers",
                    "107":"Grimoire_Block",
                    "108":"Durruti_Block",
                    "109":"Blue_Doctor_Project",
                    "110":"Enlightenment_Towers",
                    "111":"Renaissance_Block",
                    "112":"Slum_City",
                    "113":"Warehouse_One",
                    "114":"Warehouse_Two",
                    "115":"Warehouse_Three",
                    "116":"Warehouse_Four",
                    "117":"Warehouse_Five",
                    "118":"Warehouse_Six",
                    "119":"Warehouse_Seven",
                    "120":"Warehouse_Eight",
                    "121":"Warehouse_Nine",
                    "122":"Warehouse_Ten",
                    "123":"Warehouse_Eleven",
                    "124":"Warehouse_Twelve",
                    "125":"Energen_Building",
                    "126":"Midas_Building",
                    "127":"Recyclotorium_One",
                    "128":"Recyclotorium_Two",
                    "129":"Recyclotorium_Three",
                    "130":"Temple_of_the_Apocalypse",
                    "131":"Temple_of_the_Millenium",
                    "132":"Temple_of_the_Visitors",
                    "133":"Temple_of_Humility",
                    "134":"Temple_of_Doom",
                    "135":"Temple_of_Sanity"
					},
				
		"facility":{
                    "0":"Earth",
                    "1":"Corridor 1",
                    "2":"Corridor 2",
                    "3":"Corridor 3",
                    "4":"Corridor 4",
                    "5":"Corridor 5",
                    "6":"Corridor 6",
                    "7":"Corridor 7",
                    "8":"Corridor 8",
                    "9":"Corridor 9",
                    "10":"Corridor 10",
                    "11":"Corridor 11",
                    "12":"Corridor 12",
                    "13":"Corridor 13",
                    "14":"Corridor 14",
                    "15":"Corridor 15",
                    "16":"Access Lift",
                    "17":"Living Quarters",
                    "18":"Stores",
                    "19":"Cells",
                    "20":"Medical Bay",
                    "21":"Training Area",
                    "22":"Psi-gym",
                    "23":"Security Station",
                    "24":"Advanced Security Station",
                    "25":"Vehicle Repair Bay",
                    "26":"Biochemistry Lab",
                    "27":"Advanced Biochemistry Lab",
                    "28":"Quantum Physics Lab",
                    "29":"Advanced Quantum Physics Lab",
                    "30":"Alien Containment",
                    "31":"Advanced Alien Containment",
                    "32":"Workshop",
                    "33":"Advanced Workshop",
                    "-53":"Part of the factory",
                    "-54":"Part of the factory",
                    "-55":"Part of the factory"
                   },
	    "craft":{
                    "0":"Alien Probe",
                    "1":"Alien Scout",
                    "2":"Alien Transporter",
                    "3":"Alien Fast Attack Ship",
                    "4":"Alien Destroyer",
                    "5":"Alien Assault Ship",
                    "6":"Alien Bomber",
                    "7":"Alien Escort",
                    "8":"Alien Battleship",
                    "9":"Alien Mothership",
                    "10":"Police Hovercar",
                    "11":"Airtaxi",
                    "12":"Rescue Transport",
                    "13":"Construction Vehicle",
                    "14":"Airtrans",
                    "15":"Space Liner",
                    "16":"Phoenix Hovercar",
                    "17":"Hoverbike",
                    "18":"Valkyrie Interceptor",
                    "19":"Hawk Air Warrior",
                    "20":"Dimension Probe",
                    "21":"Biotrans",
                    "22":"Explorer",
                    "23":"Retaliator",
                    "24":"Annihilator",
                    "25":"Autotaxi",
                    "26":"Autotrans",
                    "27":"Police Car",
                    "28":"Civilian Car",
                    "29":"Stormdog",
                    "30":"Wolfhound APC",
                    "31":"Blazer Turbo Bike",
                    "32":"Griffon AFV",
                    "33":"Overspawn"

                   },
		"veh_shadow_offset":{
			        "-1":"Not used",
                    "88":"Alien Probe",
                    "89":"Alien Scout",
                    "90":"Alien Transporter",
                    "91":"Alien Fast Attack Ship",
                    "92":"Alien Destroyer",
                    "93":"Alien Assault Ship",
                    "94":"Alien Bomber",
                    "95":"Alien Escort",
                    "96":"Alien Battleship",
                    "97":"Alien Mothership",
                    "48":"Police H_car/Airtaxi",
                    "56":"Rescue Transport",
                    "24":"Construction Vehicle",
                    "98":"Space Liner",
                    "48":"Ph_Hovercar/Airtrans",
                    "40":"Hoverbike",
                    "80":"Valkyrie Interceptor",
                    "16":"Hawk Air Warrior",
                    "64":"Dimension Probe",
                    "8":"Biotrans",
                    "32":"Explorer",
                    "72":"Retaliator",
                    "0":"Other 10 type"
                   },   
		"agent_equipment":{
                    "0":"Empty",
                    "1":"Megapol AP Grenade",
                    "2":"Megapol Stun Grenade",
                    "3":"Megapol Smoke Grenade",
                    "4":"Marsec Proximity Mine",
                    "5":"Marsec High Explosive",
                    "6":"Megapol Lawpistol",
                    "7":"Megapol Lawpistol Clip",
                    "8":"Marsec M4000 Machine Gun",
                    "9":"Marsec M4000 Gun Clip",
                    "10":"Megapol Laser Sniper Gun",
                    "11":"Megapol Laser Pod",
                    "12":"Megapol Auto Cannon",
                    "13":"Auto Cannon AP Clip",
                    "14":"Auto Cannon HE Clip",
                    "15":"Auto Cannon IN Clip",
                    "16":"Megapol Plasma Gun",
                    "17":"Megapol Plasma Pod",
                    "18":"Marsec Heavy Launcher",
                    "19":"Heavy Launcher AG Missile",
                    "20":"Heavy Launcher HE Missile",
                    "21":"Heavy Launcher IN Missile",
                    "22":"Marsec MiniLauncher",
                    "23":"MiniLauncher AG Missile",
                    "24":"MiniLauncher HE Missile",
                    "25":"MiniLauncher IN Missile",
                    "26":"Megapol Stun Grapple",
                    "27":"Alien Gas Grenade",
                    "28":"Tracker Gun Clip",
                    "29":"Tracker Gun",
                    "30":"Multi-Tracker",
                    "31":"PSI-Grenade",
                    "32":"ForceWeb",
                    "33":"Toxigun",
                    "34":"Toxigun A-Clip",
                    "35":"Toxigun B-Clip",
                    "36":"Toxigun C-Clip",
                    "37":"Dimension Destabiliser",
                    "38":"Mind Shield",
                    "39":"Mind Bender",
                    "40":"Alien Detector",
                    "41":"Disruptor Gun",
                    "42":"Devastator Cannon",
                    "43":"Boomeroid",
                    "44":"Power Sword",
                    "45":"Brainsucker Launcher",
                    "46":"Entropy Launcher",
                    "47":"Dimension Missile Launcher",
                    "48":"Dimension Missile",
                    "49":"Vortex Mine",
                    "50":"Personal Disruptor Shield",
                    "51":"Personal Teleporter",
                    "52":"Personal Cloaking Field",
                    "53":"Dimension Force Field",
                    "54":"Energy Pod",
                    "55":"Medi-kit",
                    "56":"Motion Scanner",
                    "57":"Brainsucker Pod",
                    "58":"Entropy Pod",
                    "59":"Incendiary Grenade",
                    "60":"Megapol Leg Armor",
                    "61":"Megapol Body Armor",
                    "62":"Megapol Right Arm Armor",
                    "63":"Megapol Left Arm Armor",
                    "64":"Megapol Helmet",
                    "65":"Marsec Leg Units",
                    "66":"Marsec Body Unit",
                    "67":"Marsec Right Arm Unit",
                    "68":"Marsec Left Arm Unit",
                    "69":"Marsec Head Unit",
                    "70":"X-COM Leg Shields",
                    "71":"X-COM Body Shield",
                    "72":"X-COM Right Arm Shield",
                    "73":"X-COM Left Arm Shield",
                    "74":"X-COM Head Shield",
                    "75":"Psimorphs Mindbender",
                    "76":"Megaspawns Disruptor",
                    "77":"Megaspawns Launcher",
                    "78":"Spitters Vomit Funnel",
                    "79":"Multiworms Spit",
                    "80":"Alien Eggs Vomit Tube",
                    "81":"Hyperworms Bite",
                    "82":"Queenspawns Tentacles",
                    "83":"Poppers Bomb",
                    "84":"Psiclone",
                    "85":"Elerium",
                    "86":"Alien Artifact",
                    "-1":"Filler",
                    "255":"Empty"
                   },
        "agent_equipment_type":{
                    "0":"None",
                    "1":"Megapol Stun Grenade",
                    "2":"Megapol Smoke Grenade",
                    "3":"Marsec Proximity Mine",
                    "4":"Marsec High Explosive",
                    "5":"Megapol Lawpistol",
                    "6":"Marsec M4000 Machine Gun",
                    "7":"Megapol Laser Sniper Gun",
                    "8":"Auto Cannon (AP)",
                    "9":"Auto Cannon (HE)",
                    "10":"Auto Cannon (IN)",
                    "11":"Megapol Plasma Gun",
                    "12":"Heavy Launcher (AG)",
                    "13":"Heavy Launcher (HE)",
                    "14":"Heavy Launcher (IN)",
                    "15":"MiniLauncher (AG)",
                    "16":"MiniLauncher (HE)",
                    "17":"MiniLauncher (IN)",
                    "18":"PSI-Grenade",
                    "19":"Toxigun (A)",
                    "20":"Toxigun (B)",
                    "21":"Toxigun (C)",
                    "22":"Disruptor Gun",
                    "23":"Devastator Cannon",
                    "24":"Boomeroid",
                    "25":"Power Sword",
                    "26":"Brainsucker Launcher",
                    "27":"Entropy Launcher",
                    "28":"Dimension Missile Launcher",
                    "29":"Vortex Mine",
                    "30":"Tracker Gun",
                    "31":"Alien Gas Grenade",
                    "32":"Megapol Stun Grapple",
                    "33":"Forceweb",
                    "34":"Dimension Distabiliser",
                    "35":"Incendiary Grenade",
                    "36":"Megaspawns Disruptor",
                    "37":"Megaspawns Launcher",
                    "38":"Spitters Vomit Funnel",
                    "39":"Multiworms Spit",
                    "40":"Alien Eggs Vomit Tube",
                    "41":"Hyperworms Bite",
                    "42":"Queenspawns Tentacles",
                    "43":"Poppers Bomb",
                    "-1":"Filler",
                    "255":"Empty"
                   },
		"craft_equip":{
			        "-1":"not used",
			        "0":"Empty section",
                    "1":"Bolter 4000 Laser Gun",
                    "2":"Lancer 7000 Laser Gun",
                    "3":"Rendor Plasma Gun",
                    "4":"Lineage Plasma Cannon",
                    "5":"Plasma Multi-System",
                    "6":"Light Disruptor Beam",
                    "7":"Medium Disruptor Beam",
                    "8":"Heavy Disruptor Beam",
                    "9":"40mm Auto Cannon",
                    "10":"Janitor Missile Array",
                    "11":"Justice Missile Launcher",
                    "12":"Prophet Missile Array",
                    "13":"Retribution Missile Launcher",
                    "14":"Disruptor Bomb Launcher",
                    "15":"Stasis Bomb Launcher",
                    "16":"Disruptor Multi-Bomb Launcher",
                    "17":"Laser Defense Array",
                    "18":"Plasma Defense Array",
                    "19":"SD Standard",
                    "20":"SD Deluxe",
                    "21":"SD Sports",
                    "22":"SD Turbo",
                    "23":"SD Elite",
                    "24":"SD Special",
                    "25":"40mm Auto Cannon Turret",
                    "26":"Airguard Anti-Air Cannon",
                    "27":"GLM Array",
                    "28":"Plasma Turret Cannon",
                    "29":"GLM Air defense",
                    "30":"Rumble Cannon",
                    "31":"Metro Roadhog",
                    "32":"Metro Roadgrav",
                    "33":"Metro Turbograv",
                    "34":"Metro Powergrav",
                    "35":"Metro Multipower Plus",
                    "36":"Light Weapons Control",
                    "37":"Medium Weapons Control",
                    "38":"Heavy Weapons Control",
                    "39":"Advanced Control System",
                    "40":"Cargo Module",
                    "41":"Passenger Module",
                    "42":"Bio-Transport Module",
                    "43":"Missile Evasion Matrix",
                    "44":"Small Disruption Shield",
                    "45":"Large Disruption Shield",
                    "46":"Cloaking Field",
                    "47":"Teleporter",
                    "48":"Dimension Shifter",
					"255":"Filler"
                   },
		"building_function":{
                    "0":"-",
                    "1":"Senate",
                    "2":"Police Station",
                    "3":"Hospital",
                    "4":"School",
                    "5":"Rescue Station",
                    "6":"Offices",
                    "7":"Corporate HQ",
                    "8":"Space Port",
                    "9":"Sensodrome",
                    "10":"Astrodome",
                    "11":"Procreation Park",
                    "12":"Shopping Mall",
                    "13":"Car Park",
                    "14":"Apartments",
                    "15":"Luxury Apartments",
                    "16":"Hotel",
                    "17":"Atmosphere Processor",
                    "18":"Hydro-Farm",
                    "19":"Sewage Works",
                    "20":"Water Purifier",
                    "21":"Appliances Factory",
                    "22":"Arms Factory",
                    "23":"Robot Factory",
                    "24":"Car Factory",
                    "25":"Flyer Factory",
                    "26":"Large Flyer Factory",
                    "27":"Construction Factory",
                    "28":"Slums",
                    "29":"Ruins",
                    "30":"Warehouse",
                    "31":"Space Ship",
                    "32":"Power Station",
                    "33":"Recyclotorium",
                    "34":"Outdoor Parks",
                    "35":"People Tubes",
                    "36":"Temple of Sirius",
                    "37":"X-COM Base"

                   }, 
		"ufos":{
                    "0":"UFOs",
                    "1":"Incubator Chamber",
                    "2":"Spawning Chamber",
                    "3":"Food Chamber",
                    "4":"Megapod Chamber",
                    "5":"Sleeping Chamber",
                    "6":"Organic Factory",
                    "7":"Alien Farm",
                    "8":"Control Chamber",
                    "9":"Maintenance Factory",
                    "10":"Dimension Gate Generator",
                    "11":"Transporter",
                    "12":"Fast Attack ship",
                    "13":"Destroyer",
                    "14":"Assault craft",
                    "15":"Bomber",
                    "16":"Escort",
                    "17":"Battleship",
                    "18":"Mothership"

                   },
		"Organizations":{
                    "0":"X-COM",
                    "1":"Alien",
                    "2":"Government",
                    "3":"Megapol",
                    "4":"Cult of Sirius",
                    "5":"Marsec",
                    "6":"Superdynamics",
                    "7":"General Metro",
                    "8":"Cyberweb",
                    "9":"Transtellar",
                    "10":"Solmine",
                    "11":"Sensovision",
                    "12":"Lifetree",
                    "13":"Nutrivend",
                    "14":"Evonet",
                    "15":"Sanctuary Clinic",
                    "16":"Nanotech",
                    "17":"Energen",
                    "18":"Synthemesh",
                    "19":"Gravball League",
                    "20":"Psyke",
                    "21":"Diablo",
                    "22":"Osiron",
                    "23":"S.E.L.F.",
                    "24":"Mutant Alliance",
                    "25":"Extropians",
                    "26":"Technocrats",
                    "27":"Civilian",
                    "-1":"None"


                   },
	    "ammo":{
                    "0":"Fusion Powerfuel",
                    "1":"Elerium-115",
                    "2":"Zorium",
                    "3":"Multi-Cannon Round",
                    "4":"Janitor Missile",
                    "5":"Justice Missile",
                    "6":"Prophet Missile",
                    "7":"Retribution Missile",
                    "8":"Disruptor Bomb",
                    "9":"Stasis Bomb",
                    "10":"Disruptor Multi-Bomb",
                    "11":"Repeater 40mm Cannon Round",
                    "12":"Airguard 52mm Cannon Round",
                    "13":"Ground Launched Missile",
                    "14":"Air Defense Missile",
                    "15":"#Megapol Lawpistol Clip",
                    "16":"#Marsec M4000 Gun Clip",
                    "17":"#Megapol Laser Pod",
                    "18":"#Auto Cannon AP Clip",
                    "19":"#Auto Cannon HE Clip",
                    "20":"#Auto Cannon I Clip",
                    "21":"#Megapol Plasma Pod",
                    "22":"#Heavy Launcher Alien Gas Missile",
                    "23":"#Heavy Launcher Blaster MIssile",
                    "24":"#Heavy Launcher Incendiary Missile",
                    "25":"#MiniLauncher Alien Gas Missile",
                    "26":"#MiniLauncher HE Missile",
                    "27":"#MiniLauncher I Missile",
                    "28":"#Toxigun A-Clip",
                    "29":"#Toxigun B-Clip",
                    "30":"#Toxigun C-Clip",
                    "31":"#Brainsucker Pod",
                    "32":"#Entropy Pod",
                    "33":"#Dimension Missile",
                    "34":"#Tracker Gun Clip",
                    "35":"not used",
                    "36":"not used",
                    "37":"not used",
                    "38":"not used",
                    "39":"not used",
                    "40":"not used",
                    "41":"not used",
                    "42":"not used",
                    "43":"not used",
                    "44":"not used"

                   },
		"ufos_build":{
                    "0":"Incubator Chamber",
                    "1":"Spawning Chamber",
                    "2":"Food Chamber",
                    "3":"Megapod Chamber",
                    "4":"Sleeping Chamber",
                    "5":"Organic Factory",
                    "6":"Alien Farm",
                    "7":"Control Chamber",
                    "8":"Maintenance Factory",
                    "9":"Dimension Gate Generator",
                    "10":"Dimension Gates",
                    "11":"The Alien Dimension",
                    "12":"One Way To Win"

                   },
		"research":{
                    "0":"Dimension Gates",
                    "1":"The Alien Dimension",
                    "2":"Dimension Probe",
                    "3":"Bio-Transport",
                    "4":"Explorer",
                    "5":"Retaliator",
                    "6":"Annihilator",
                    "7":"Brainsucker Pods",
                    "8":"Brainsucker Autopsy",
                    "9":"Brainsucker",
                    "10":"Multiworm Egg Autopsy",
                    "11":"Multiworm Egg",
                    "12":"Multiworm Autopsy",
                    "13":"Multiworm",
                    "14":"Hyperworm Autopsy",
                    "15":"Hyperworm",
                    "16":"Chrysalis Autopsy",
                    "17":"Chrysalis",
                    "18":"Anthropod Autopsy",
                    "19":"Anthropod",
                    "20":"Psimorph Autopsy",
                    "21":"Psimorph",
                    "22":"Spitter Autopsy",
                    "23":"Spitter",
                    "24":"Megaspawn Autopsy",
                    "25":"Megaspawn",
                    "26":"Popper Autopsy",
                    "27":"Popper",
                    "28":"Skeletoid Autopsy",
                    "29":"Skeletoid",
                    "30":"Micronoid Autopsy",
                    "31":"Micronoid",
                    "32":"Queenspawn Autopsy",
                    "33":"Queenspawn",
                    "34":"Overspawn Autopsy",
                    "35":"Overspawn Autopsy",
                    "36":"The Alien Genetic Structure",
                    "37":"The Alien Life Cycle",
                    "38":"The Real Alien Threat",
                    "39":"Biological Warfare",
                    "40":"Toxin Type B",
                    "41":"Toxin Type C",
                    "42":"Alien Gas",
                    "43":"Advanced Security Station",
                    "44":"Advanced Biochemistry Lab",
                    "45":"Advanced Quantum Physics Lab",
                    "46":"Advanced Alien Containment",
                    "47":"Advanced Workshop",
                    "48":"Disruptor Gun",
                    "49":"Devastator Cannon",
                    "50":"Boomeroid",
                    "51":"Brainsucker Launcher",
                    "52":"Entropy Launcher",
                    "53":"Entropy Pod",
                    "54":"Dimension Missile Launcher",
                    "55":"Dimension Missile",
                    "56":"Vortex Mine",
                    "57":"Personal Disruptor Shield",
                    "58":"Personal Teleporter",
                    "59":"Personal Cloaking Field",
                    "60":"Dimension Destabiliser",
                    "61":"Disruptor Armor",
                    "62":"Light Disruptor Beam",
                    "63":"Medium Disruptor Beam",
                    "64":"Heavy Disruptor Beam",
                    "65":"Disruptor Inversion Bomb",
                    "66":"Stasis Field Bomb",
                    "67":"Disruptor Multi-Bomb",
                    "68":"X-COM Advanced Control System",
                    "69":"Bio-Transport Module",
                    "70":"Small Disruption Shield",
                    "71":"Large Disruption Shield",
                    "72":"Cloaking Field",
                    "73":"Teleporter",
                    "74":"Dimension Shifter",
                    "75":"Alien Propulsion System",
                    "76":"Alien Control System",
                    "77":"Alien Energy Source",
                    "78":"UFO type 1",
                    "79":"UFO type 2",
                    "80":"UFO type 3",
                    "81":"UFO type 4",
                    "82":"UFO type 5",
                    "83":"UFO type 6",
                    "84":"UFO type 7",
                    "85":"UFO type 8",
                    "86":"UFO type 9",
                    "87":"UFO type 10",
                    "88":"Alien building",
                    "89":"Alien building",
                    "90":"Alien building",
                    "91":"Alien building",
                    "92":"Alien building",
                    "93":"Alien building",
                    "94":"Alien building",
                    "95":"Alien building",
                    "96":"Alien building",
                    "97":"Alien building",
                    "98":"One way to win"

                   },
		"manufacturing data":{
                    "0":"Dimension Probe",
                    "1":"Bio-Transport",
                    "2":"Explorer",
                    "3":"Retaliator",
                    "4":"Annihilator",
                    "5":"Light Disruptor Beam",
                    "6":"Medium Disruptor Beam",
                    "7":"Heavy Disruptor Beam",
                    "8":"Disruptor Inversion Bomb launcher",
                    "9":"Disruptor Inversion Bomb",
                    "10":"Stasis Field Bomb launcher",
                    "11":"Stasis Field Bomb",
                    "12":"Disruptor Multi-Bomb launcher",
                    "13":"Disruptor Multi-Bomb",
                    "14":"X-COM Advanced Control System",
                    "15":"Bio-Transport Module",
                    "16":"Small Disruption Shield",
                    "17":"Large Disruption Shield",
                    "18":"Cloaking Field",
                    "19":"Teleporter",
                    "20":"Dimension Shifter",
                    "21":"Toxigun",
                    "22":"Toxin Type A",
                    "23":"Toxin Type B",
                    "24":"Toxin Type C",
                    "25":"Alien Gas Grenade",
                    "26":"Heavy Launcher Alien Gas Missile",
                    "27":"Mini Launcher Alien Gas Missile",
                    "28":"Disruptor Gun",
                    "29":"Devastator Cannon",
                    "30":"Boomeroid",
                    "31":"Dimension Missile Launcher",
                    "32":"Dimension Missile",
                    "33":"Vortex Mine",
                    "34":"Personal Disruptor Shield",
                    "35":"Personal Teleporter",
                    "36":"Personal Cloaking Field",
                    "37":"Dimension Destabiliser",
                    "38":"Disruptor Armor (legs)",
                    "39":"Disruptor Armor (torso)",
                    "40":"Disruptor Armor (right arm)",
                    "41":"Disruptor Armor (left arm)",
                    "42":"Disruptor Armor (head)"


                   },
	    "alien":{
                    "0":"Alien Egg",
                    "1":"Brainsucker",
                    "2":"Multiworm",
                    "3":"Hyperworm",
                    "4":"Chrysalis",
                    "5":"Anthropod",
                    "6":"Skeletoid",
                    "7":"Spitter",
                    "8":"Popper",
                    "9":"Megaspawn",
                    "10":"Psimorph",
                    "11":"Queenspawn",
                    "12":"Micronoid Aggregate",
                    "13":"Brainsucker Pod",
                    "14":"Overspawn"

                   },
	    "rang":{
                    "0":"Rookie",
                    "1":"Squaddie",
                    "2":"Squad leader",
                    "3":"Sergeant",
                    "4":"Captain",
                    "5":"Colonel",
                    "6":"Commander"

                   },
	    "inventory":{
                    "0":"Ammo Clip",
                    "1":"Motion Scanner",
                    "2":"Structure Probe",
                    "3":"Vortex Analyser",
                    "4":"Multitracker",
                    "5":"Mind Shield",
                    "6":"Mind Bender",
                    "7":"Alien Detector",
                    "8":"Personal Disruptor Shield",
                    "9":"Personal Teleporter",
                    "10":"Personal Cloaking Field",
                    "11":"Dimension Force Field",
                    "12":"Medi-Kit"

                   },
	    "people":{
                    "0":"X-COM Agent",
                    "1":"X-COM Biochemist",
                    "2":"X-COM Mechanic",
                    "3":"X-COM Quantum Physicist",
                    "4":"Gang leader",
                    "5":"Corporate Boss",
                    "6":"Cult Leader",
                    "7":"Politician",
                    "8":"Chief of Police",
                    "9":"Corporate hood",
                    "10":"Police",
                    "11":"Gangster",
                    "12":"Cultist",
                    "13":"Building security",
                    "14":"Android",
                    "15":"Alien Grey",
                    "16":"Upper Class Female",
                    "17":"Upper Class Female",
                    "18":"Upper Class Female",
                    "19":"Upper Class Male",
                    "20":"Upper Class Male",
                    "21":"Upper Class Male",
                    "22":"Civilian Female",
                    "23":"Civilian Female",
                    "24":"Civilian Female",
                    "25":"Civilian Male",
                    "26":"Civilian Male",
                    "27":"Civilian Male",
                    "28":"Lower Class Male",
                    "29":"Lower Class Male",
                    "30":"Lower Class Male",
                    "31":"Lower Class Female",
                    "32":"Lower Class Female",
                    "33":"Lower Class Female",
                    "34":"Multiworm egg",
                    "35":"Brainsucker",
                    "36":"Multiworm",
                    "37":"Hyperworm",
                    "38":"Chrysalis",
                    "39":"Anthropod",
                    "40":"Skeletoid",
                    "41":"Spitter",
                    "42":"Popper",
                    "43":"Megaspawn",
                    "44":"Psimorph",
                    "45":"Queenspawn",
                    "46":"Micronoid Aggregate"

                   },
	    "gas":{
                    "0":"Smoke",
                    "1":"Anti-Alien Gas",
                    "2":"Incendiary",
                    "3":"Stun Gas",
                    "4":"Explosive",
                    "5":"Stun",
                    "6":"Psionic Blast",
                    "7":"Armor Piercing",
                    "8":"Laser Beam",
                    "9":"Plasma",
                    "10":"Toxin A",
                    "11":"Toxin B",
                    "12":"Toxin C",
                    "13":"Dimension Destabiliser",
                    "14":"Disruptor Beam",
                    "15":"Explosive",
                    "16":"Entropy Enzyme",
                    "17":"Falling Object",
                    "18":"Brainsucker"
   
                   },
        "difficulty_level":{
                    "0":"Novice",
                    "1":"Easy",
					"2":"Medium",
                    "3":"Hard",
                    "4":"Superhuman"
                   },

        "game_speed":{
                    "0":"Pause",
                    "1":"Slow speed",
                    "2":"Normal speed",
					"4":"Double speed",
                    "6":"Quadruple speed",
                    "60":"Ultra fast"
                         },

	    "map_flag":      {
                              "0":"City",
                              "1":"Alien d-n"
                         },
        "research_flag":      {
                              "0":"not_researched",
                              "1":"researched"
                         },
        "agent_assignment":      {
                              "1":"building",
                              "2":"ppl tube",
                              "3":"vehicle",
                              "-1":"inactive"
                         },
	    "ufo_arrived_city":  {
                              "0":"all",
                              "1":"not_all"
                             },
		"rank":             {
                              "0":"Rookie",
                              "1":"Squaddie",
							  "2":"Squad_Leader",
							  "3":"Sergeant",
							  "4":"Captain",
							  "5":"Colonel",
							  "6":"Commander"
                             },
	    "role":             {
                              "0":"X-COM_agent",
                              "1":"Biochemist",
							  "2":"Engineer",
							  "3":"Quantum_Physicist"
                             },
	    "veh_animation_type":{
                              "0":"Sequentional",
                              "1":"Directional"
                             },
				   
		"veh_movement_type":{
							 "-1":"not used",
							 "0":"road",
							 "1":"flying",
							 "2":"overspawn"
							},
		"veh_target_type":{
							 "-1":"None",
							 "0":"build",
							 "1":"vehicle",
							 "2":"map_position"
							},
				   
	    "veh_enable_weapon":{
							"0":"disable",
							"1":"enable"
							},
		"hire":{
							"0":"not hired",
							"2":"hired"
							},
		"gender":{
							"0":"male",
							"1":"female",
							"2":"android"
							},
		"road_end":{
							"0":"no shed",
							"1":"shed"
							},
		"like_alien":{
							"0":"No",
							"1":"Yes"
							},
		"purchas":{
							"0":"No",
							"1":"Yes"
							},
		"agent_assignment_type":{
							"1":"building",
							"2":"tube",
							"3":"vehicle",
							"-1":"inactive"
							},
		"agent_order":{
							"0":"no_order",
							"1":"return_to_base",
							"2":"unk",
							"3":"unk",
							"4":"tailing",
							"5":"spying",
							"6":"unk",
							"7":"unk",
							"8":"unk",
							"9":"unk",
							"10":"unk",
							"11":"unk",
							"12":"unk"
							},
		"vehicle_mission":{
							"0":"None",
							"1":"Attack_near_portal_bld",
							"2":"Micronoid_rain",
							"3":"Alien_drop",
							"4":"Random_bld_attack",
							"5":"Overspawn_drop"
							},
        "score":{
                    "0":"tactical_score",
                    "1":"tactical_score_all",
                    "2":"Research_Completed",
					"3":"Research_Completed_all",
                    "4":"Alien_incid",
                    "5":"Alien_incid_all",
                    "6":"Ufo_shot_down",
                    "7":"Ufo_shot_down_all",
                    "8":"Xcom_veh_destr",
                    "9":"Xcom_veh_destr_all",
                    "10":"UFO_Incursions",
                    "11":"UFO_Incursions_all",
                    "12":"Damage_to_City",
                    "13":"Damage_to_City_all",
                    "14":"Week_score",
                    "15":"Total_score"
                         },
		"building_type":{
							"0":"Corporate_HQ",
							"1":"Property",
							"2":"Financial_services",
							"3":"Import/Export",
							"4":"Security_services",
							"5":"Transport_services",
							"6":"Administration",
							"7":"Genetics"
							},
		"rules_of_engagement":{
							"0":"Evasive",
							"1":"Defensive",
							"2":"Standard",
							"3":"Aggressive",
							"4":"unkn",
							"5":"Attack_building(AI)",
							"6":"Police(AI)",
							"7":"Alien_drop(AI)",
							"8":"Micronoid_rain(AI)",
							"9":"unkn",
							"10":"Overspawn_drop(AI)",
							"11":"Escort(AI)",
							"12":"unkn",
							"13":"unkn",
							"14":"unkn"

							},
		"cargo_item_type":  {
		                      "0":"unused",
                              "1":"agent",
                              "2":"vehicle",
                              "3":"fuel",
                              "4":"alien_alive",
                              "5":"alien_died"
                             },
							
		"craft_equipment_layout":{
                    "0":"UFO",
                    "1":"Police Hovercar",
                    "2":"Airtaxi",
                    "3":"Rescue Transport",
                    "4":"Construction Vehicle",
                    "5":"Airtrans",
                    "6":"Space Liner",
                    "7":"Phoenix Hovercar",
                    "8":"Hoverbike",
                    "9":"Valkyrie Interceptor",
                    "10":"Hawk Air Warrior",
                    "11":"Dimension Probe",
                    "12":"Biotrans",
                    "13":"Explorer",
                    "14":"Retaliator",
                    "15":"Annihilator",
                    "16":"Autotaxi",
                    "17":"Autotrans",
                    "18":"Police Car",
                    "19":"Civilian Car",
                    "20":"Stormdog",
                    "21":"Wolfhound APC",
                    "22":"Blazer Turbo Bike",
                    "23":"Griffon AFV"
                   },
        "agents_inventory":{
                    "0":"inventory 1",
                    "1":"inventory 2",
                    "2":"inventory 3",
                    "3":"inventory 4",
                    "4":"inventory 5",
                    "5":"inventory 6",
                    "6":"inventory 7",
                    "7":"inventory 8",
                    "8":"inventory 9",
                    "9":"inventory 10",
                    "10":"inventory 11",
                    "11":"inventory 12",
                    "12":"inventory 13",
                    "13":"inventory 14",
                    "14":"inventory 15",
                    "15":"inventory 16",
                    "16":"inventory 17",
                    "17":"inventory 18",
                    "18":"inventory 19",
                    "19":"inventory 20",
                    "20":"inventory 21",
                    "21":"inventory 22",
                    "22":"inventory 23",
                    "23":"inventory 24",
                    "24":"inventory 25",
                    "25":"inventory 26",
                    "26":"inventory 27",
                    "27":"inventory 28",
                    "28":"inventory 29",
                    "29":"inventory 30",
                    "30":"inventory 31",
                    "31":"inventory 32",
                    "32":"inventory 33",
                    "33":"inventory 34",
                    "34":"inventory 35",
                    "35":"inventory 36",
                    "36":"inventory 37",
                    "37":"inventory 38",
                    "38":"inventory 39",
                    "39":"inventory 40",
                    "40":"inventory 41",
                    "41":"inventory 42",
                    "42":"inventory 43",
                    "43":"inventory 44",
                    "44":"inventory 45",
                    "45":"inventory 46",
                    "46":"inventory 47",
                    "47":"inventory 48",
                    "48":"inventory 49",
                    "49":"inventory 50",
                    "50":"inventory 51",
                    "51":"inventory 52",
                    "52":"inventory 53",
                    "53":"inventory 54",
                    "54":"inventory 55",
                    "55":"inventory 56",
                    "56":"inventory 57",
                    "57":"inventory 58",
                    "58":"inventory 59",
                    "59":"inventory 60",
                    "60":"Tinventory 61",
                    "61":"inventory 62",
                    "62":"inventory 63",
                    "63":"inventory 64",
                    "64":"inventory 65",
                    "65":"inventory 66",
                    "66":"inventory 67",
                    "67":"inventory 68",
                    "68":"inventory 69",
                    "69":"inventory 70",
                    "70":"inventory 71",
                    "71":"inventory 72",
                    "72":"inventory 73",
                    "73":"inventory 74",
                    "74":"inventory 75",
                    "75":"inventory 76",
                    "76":"inventory 77",
                    "77":"inventory 78",
                    "78":"inventory 79",
                    "79":"inventory 80",
                    "80":"inventory 81",
                    "81":"inventory 82",
                    "82":"inventory 83",
                    "83":"inventory 84",
                    "84":"inventory 85",
                    "85":"inventory 86",
                    "86":"inventory 87",
                    "87":"inventory 88",
                    "88":"inventory 89",
                    "89":"inventory 90",
                    "90":"inventory 91",
                    "91":"inventory 92",
                    "92":"inventory 93",
                    "93":"inventory 94",
                    "94":"inventory 95",
                    "95":"inventory 96",
                    "96":"inventory 97",
                    "97":"inventory 98",
                    "98":"inventory 99",
                    "99":"inventory 100",
                    "100":"inventory 101",
                    "101":"inventory 102",
                    "102":"inventory 103",
                    "103":"inventory 104",
                    "104":"inventory 105",
                    "105":"inventory 106",
                    "106":"inventory 107",
                    "107":"inventory 108",
                    "108":"inventory 109",
                    "109":"inventory 110",
                    "110":"inventory 111",
                    "111":"inventory 112",
                    "112":"inventory 113",
                    "113":"inventory 114",
                    "114":"inventory 115",
                    "115":"inventory 116",
                    "116":"inventory 117",
                    "117":"inventory 118",
                    "118":"inventory 119",
                    "119":"inventory 120",
                    "120":"inventory 121",
                    "121":"inventory 122",
                    "122":"inventory 123",
                    "123":"inventory 124",
                    "124":"inventory 125",
                    "125":"inventory 126",
                    "126":"inventory 127",
                    "127":"inventory 128",
                    "128":"inventory 129",
                    "129":"inventory 130",
                    "130":"inventory 131",
                    "131":"inventory 132",
                    "132":"inventory 133",
                    "133":"inventory 134",
                    "134":"inventory 135",
                    "135":"inventory 136",
                    "136":"inventory 137",
                    "137":"inventory 138",
                    "138":"inventory 139",
                    "139":"inventory 140",
                    "140":"inventory 141",
                    "141":"inventory 142",
                    "142":"inventory 143",
                    "143":"inventory 144",
                    "144":"inventory 145",
                    "145":"inventory 146",
                    "146":"inventory 147",
                    "147":"inventory 148",
                    "148":"inventory 149",
                    "149":"inventory 150",
                    "-1":"None"
                   },
        "tile_type":{
				    "0":"General",
				    "1":"Road",
				    "2":"PPL tube junc",
					"3":"PPL tube",
					"4":"City wall"
				  },
	    "road_type":{
				    "0":"Straight/Bend",
				    "1":"junc/Crossroad",
				    "2":"Terminal"
				  },
	    "connect":{
				    "0":"No",
				    "1":"Yes"
				  },
	    "walk_type":{
				    "0":"None",
				    "1":"Into",
				    "2":"Onto"
				  },
		"demension":{
				    "0":"in City",
				    "1":"Alien Dimension"
				  },
		"portal_home":{
				    "-1":"in City",
				    "0":"Alien Dimension"
				  },
		"researched":{
				    "0":"Not",
				    "1":"Yes"
				  },
	    "agent_equip_art":{
				    "0":"Yes",
				    "1":"No"
				  },
		"reserch_enebled":{
				    "0":"enebled",
				    "1":"disable"
				  },
		"portal_direction":{
				    "-1":"not used",
				    "1":"in Alien Dimension",
				    "0":"in City"
				  },
		"rel_tab":{
				    "0":"all",
				    "1":"allied",
				    "2":"friendly",
				    "3":"neutral",
				    "4":"unfriendly",
				    "5":"hostle"
				  },
		"pod_direction":{
		           "0":"None",
				   "255":"land in",
				    "1":"land out"

				  },
		"action_raid":{
				   "0":"Nothing",
				   "1":"Attack",
				   "2":"Raid",
				   "3":"Storm",
				   "4":"unused_1",
				   "5":"unused_2",
				   "6":"Illegal_Flayer",
				   "7":"unused_4",
				   "8":"unused_3",
				   "9":"Treaty"
				  },
	    "xcom_mission_type":{
				    "1":"Alien_building",
				    "2":"Base_mission",
				    "3":"UFO_mission",
				    "4":"Raid"
				  },
				   
		"reserch":{
				   "0":"Dimension Gates",
				   "1":"The Alien Dimension",
                   "2":"Dimension Probe",
                   "3":"Bio-Transport",
                   "4":"Explorer",
                   "5":"Retaliator",
                   "6":"Annihilator",
                   "7":"Brainsucker Pods",
                   "8":"Brainsucker Autopsy",
                   "9":"Brainsucker",
                   "10":"Multiworm Egg Autopsy",
                   "11":"Multiworm Egg",
                   "12":"Multiworm Autopsy",
                   "13":"Multiworm",
                   "14":"Hyperworm Autopsy",
                   "15":"Hyperworm",
                   "16":"Chrysalis Autopsy",
                   "17":"Chrysalis",
                   "18":"Anthropod Autopsy",
                   "19":"Anthropod",
                   "20":"Psimorph Autopsy",
                   "21":"Psimorph",
                   "22":"Spitter Autopsy",
                   "23":"Spitter",
                   "24":"Megaspawn Autopsy",
                   "25":"Megaspawn",
                   "26":"Popper Autopsy",
                   "27":"Popper",
                   "28":"Skeletoid Autopsy",
                   "29":"Skeletoid",
                   "30":"Micronoid Autopsy",
                   "31":"Micronoid",
                   "32":"Queenspawn Autopsy",
                   "33":"Queenspawn",
                   "34":"Overspawn Autopsy",
                   "35":"Overspawn",
                   "36":"The Alien Genetic Structure",
                   "37":"The Alien Life Cycle",
                   "38":"The Real Alien Threat",
                   "39":"Biological Warfare",
                   "40":"Toxin Type B",
                   "41":"Toxin Type C",
                   "42":"Alien Gas",
                   "43":"Advanced Security Station",
                   "44":"Advanced Biochemistry Lab",
                   "45":"Advanced Quantum Physics Lab",
                   "46":"Advanced Alien Containment",
                   "47":"Advanced Workshop",
                   "48":"Disruptor Gun",
                   "49":"Devastator Cannon",
                   "50":"Boomeroid",
                   "51":"Brainsucker Launcher",
                   "52":"Entropy Launcher",
                   "53":"Entropy Pod",
                   "54":"Dimension Missile Launcher",
                   "55":"Dimension Missile",
                   "56":"Vortex Mine",
                   "57":"Personal Disruptor Shield",
                   "58":"Personal Teleporter",
                   "59":"Personal Cloaking Field",
                   "60":"Dimension Destabiliser",
                   "61":"Disruptor Armor",
                   "62":"Light Disruptor Beam",
                   "63":"Medium Disruptor Beam",
                   "64":"Heavy Disruptor Beam",
                   "65":"Disruptor Inversion Bomb",
                   "66":"Stasis Field Bomb",
                   "67":"Disruptor Multi-Bomb",
                   "68":"X-COM Advanced Control System",
                   "69":"Bio-Transport Module",
                   "70":"Small Disruption Shield",
                   "71":"Large Disruption Shield",
                   "72":"Cloaking Field",
                   "73":"Teleporter",
                   "74":"Dimension Shifter",
                   "75":"Alien Propulsion System",
                   "76":"Alien Control System",
                   "77":"Alien Energy Source",
                   "78":"UFO type 1",
                   "79":"UFO type 2",
                   "80":"UFO type 3",
                   "81":"UFO type 4",
                   "82":"UFO type 5",
                   "83":"UFO type 6",
                   "84":"UFO type 7",
                   "85":"UFO type 8",
                   "86":"UFO type 9",
                   "87":"UFO type 10",
                   "88":"Alien building",
                   "89":"Alien building",
                   "90":"Alien building",
                   "91":"Alien building",
                   "92":"Alien building",
                   "93":"Alien building",
                   "94":"Alien building",
                   "95":"Alien building",
                   "96":"Alien building",
                   "97":"Alien building",
                   "98":"One way to win"
				  },
		"manufacturing_item":{
                   "0":"Dimension Probe",
                   "1":"Bio-Transport",
                   "2":"Explorer",
                   "3":"Retaliator",
                   "4":"Annihilator",
                   "5":"Light Disruptor Beam",
                   "6":"Medium Disruptor Beam",
                   "7":"Heavy Disruptor Beam",
                   "8":"Disruptor Inversion Bomb launcher",
                   "9":"Disruptor Inversion Bomb",
                   "10":"Stasis Field Bomb launcher",
                   "11":"Stasis Field Bomb",
                   "12":"Disruptor Multi-Bomb launcher",
                   "13":"Disruptor Multi-Bomb",
                   "14":"X-COM Advanced Control System",
                   "15":"Bio-Transport Module",
                   "16":"Small Disruption Shield",
                   "17":"Large Disruption Shield",
                   "18":"Cloaking Field",
                   "19":"Teleporter",
                   "20":"Dimension Shifter",
                   "21":"Toxigun",
                   "22":"Toxin Type A",
                   "23":"Toxin Type B",
                   "24":"Toxin Type C",
                   "25":"Alien Gas Grenade",
                   "26":"Heavy Launcher Alien Gas Missile",
                   "27":"Mini Launcher Alien Gas Missile",
                   "28":"Disruptor Gun",
                   "29":"Devastator Cannon",
                   "30":"Boomeroid",
                   "31":"Dimension Missile Launcher",
                   "32":"Dimension Missile",
                   "33":"Vortex Mine",
                   "34":"Personal Disruptor Shield",
                   "35":"Personal Teleporter",
                   "36":"Personal Cloaking Field",
                   "37":"Dimension Destabiliser",
                   "38":"Disruptor Armor (legs)",
                   "39":"Disruptor Armor (torso)",
                   "40":"Disruptor Armor (right arm)",
                   "41":"Disruptor Armor (left arm)",
                   "42":"Disruptor Armor (head)"
				  },


	    "tab_sub_select":{
                    "0":"field_0",
                    "1":"base_sub_tab",
					"2":"veh_sub_tab",
					"3":"agent_sub_tab",
					"4":"bio_sub_tab",
					"5":"eng_sub_tab",
					"6":"qua_sub_tab",
					"7":"ufo_sub_tab",
					"8":"field_9",
					"9":"field_10",
					"10":"org_sub_tab"
                   }


}